package co.fourapps.eyetraining;

/**
 * Created by mertsimsek on 23/12/14.
 */
public class ExerciseProps {

    public static final String distantNightDesc = "Warm up your hands by rubbing them together or sitting on them.\n\nSit down in a chair and place your elbows on your knees or a table.\n\nFace your palms toward your face and slightly cup the lower portion of your hands while keeping your fingers straight.\n\nPlace your eyes in the cups of your hands, which should gently rest above and below the  bone surrounding your eye and cheek. No portion of your hand should touch your eyeball, but it is alright if your eyelashes brush against your palm. The fingers of both hands should slightly overlap resting near the center top of your forehead. With your eyes open, be sure there is no light entering your eyes.\n\nWhile maintaining this position, relax and close your eyes while you imagine you’re looking into the distant night. Remember, your eyes are relaxed as they look out at a distance – the purpose of this exercise.\n\nYou might see flashes or floating colors, but the goal is to relax enough that you see nothing but black.\n\nPerform this exercise for at least the time specified in the training routines. Be sure your eyes feel rested and relaxed before continuing with the other exercises.";
    public static final int[] distantNightImgIds = {R.drawable.p11};

    public static final String ferrisWheelDesc = "Sit relaxed and facing straight ahead with your hands in your lap.\n\nWithout moving your head, shift your eyes to look up as high as possible.\n\nSmoothly and slowly begin to shift your eyes in a circular motion to your left without moving your head. Try to see as much of the room as possible without moving your head as your eyes trace a circle around the room.\n\nContinue shifting your eyes down, right, and back up to complete one revolution of the circle.\n\nEach quarter revolution of the circle (that is, from as far up to as far left as you can see) should take at least one full second. One revolution should be completed in no less than four seconds. Count “1 Mississippi, 2 Mississippi,” and so on to control your speed.\n\nIt is very important to have a consistent rhythm to your circle. It is common for your eyes to jump from one position to another. Think of it as a Ferris wheel that you are standing very close to while trying to look at the same cart as it rotates. It also helps to have someone else watch your eyes in the beginning to be sure they are moving slowly and smoothly.\n\nFinally, close your eyes and continue the rotation. Again, this can be done with your eyes open if you prefer. Rotate your eyes to create the largest outline of a circle within your range of comfort. The bigger the circle, the more you will feel your eyes working, but always be conscious of your personal limits and comfort level.\n\nSwitch off from a clockwise to a counterclockwise rotation as you practice this exercise.\n\nPerform the Ferris wheel for the duration specified in the training routines. Remember, smooth and slow rotations are the key.";
    public static final int[] ferrisWheelImgIds = {R.drawable.p21, R.drawable.p22, R.drawable.p23};

    public static final String threeCupsL1Desc = "Locate the chart labeled “#3 – 3 CUPS”, as well as a pen or pencil.\n\n\n\nSit relaxed and hold the chart 12 to 24 inches in front of you at eye level. If the image is not perfectly clear to you, that’s alright as long as you can make out the image. You might find it easier to place your elbows on a table so that your arms do not become fatigued as you hold the chart.\n\n\n\nHold the pen vertically between the two circles approximately 1 inch from the chart. The top of the pen should be at the same level as the image.\n\nFocus on the top of the pen as you slowly bring it toward your face. You will notice the two circles appear to become three circles. When the circles all appear to be the same shape and proportion, stop moving the pen.\n\nTry to shift your focus from the pen to the center circle. This may be difficult and could take a few days to master.\n\nOnce you can focus on the center circle, move your pen out of your line of vision while maintaining your focus. Try to see the center circle as clearly as possible. As you increase your focus you will notice that the center circle becomes three-dimensional. It will look as if you were peering down into a Styrofoam cup.\n\nFinally, look at the chart and create the three circles, the center one appearing three-dimensional, without using your pen. Look away from the chart for 1-2 seconds then again create the three circles without using your pen. Repeat this sequence for the time specified in the training routines.";
    public static final int[] threeCupsL1ImgIds = {R.drawable.p31, R.drawable.p32, R.drawable.p33, R.drawable.p34};

    public static final String threeCupsL2ADesc = "Face your chair so that you can focus on an object at least 10 feet away. It can be in the same room or outside a window – just choose a distant object.\n\nHold the “#3 – 3 CUPS” chart approximately 12 to 24 inches in front of you at eye level.\n\nPosition the chart so that as you look just over the top of it you can see the distant object. Focus on the distant object.\n\nYou should notice in your lower peripheral vision that, again, there appear to be three circles. Your eyes will feel much more relaxed than they felt when focusing on the pen in Level 1.\n\nTry to adjust your focus on the center circle as if you were looking through the chart at the distant object. In other words, maintain your point of focus on the distant object but look at the center circle. This is the only way you will be able to obtain and hold the image of the center circle. If you lose the image of the center circle, look at the distant object and it should reappear.\n\nAs you increase your focus on the center circle, you will notice that the circle again appears three-dimensional, only this time the Styrofoam cup will appear upside down as if you were looking down onto an overturned cup. Once you have obtained this center circle look away and repeat.";
    public static final int[] threeCupsL2AImgIds = {R.drawable.p34};

    public static final String threeCupsL2BDesc = "Now, try to alternate back and forth between the two different cup images. Begin by using your pen and the distant object, alternating between them to obtain the two different cup images. Focus close and you will be looking into the cup; relax your eyes and you will be looking down onto the overturned cup. Obtain a clear image of each cup before alternating your focus.\n\nFinally, try to alternate between images without using your pen or the distant object. You should be able to control your point of focus into the position needed to see these images.";
    public static final int[] threeCupsL2BImgIds = {};

    public static final String threeCupsL3ADesc = "Tape the “#3 – 3 CUPS” chart at eye level on any window that will allow you to step back from it at least 5 feet.\n\nBegin by standing 12 to 24 inches from the chart and obtain the first image from Level 1 – looking inside the cup.\n\nSlowly walk backward and maintain that image as far back as possible. Once you can no longer maintain the image of the cup, slowly walk toward the chart until you are approximately 12 inches from the window. At this time you should feel slightly cross-eyed as if you were focusing near the bridge of your nose.";
    public static final int[] threeCupsL3AImgIds = {};

    public static final String threeCupsL3BDesc = "Tape the “#3 – 3 CUPS” chart at eye level on any window that will allow you to step back from it at least five feet, the same way you did for Level 3a\n\nBegin by standing 12 to 24 inches from the chart and obtain the image from Level 2 – looking down on an overturned cup.\n\nBegin walking backward maintaining your focus on the cup. This exercise might be more difficult. If you lose the image, try to obtain it again by looking through the window. Remember to walk slowly, relax, and concentrate.\n\nOnce you can no longer maintain the image of the overturned cup, walk toward the chart until you are as close to it as you can be without the cup appearing blurry.\n\nRecord on your training routine how far you can walk backward for both Level 3a and Level 3b. You don’t necessarily need a tape measure; just write a note that you were one step in from a particular object (for example, the refrigerator or a picture on the wall). As you progress you should be able to move farther from the window while still maintaining the cup images.";
    public static final int[] threeCupsL3BImgIds = {};

    public static final String pinballDesc = "Locate the two narrow strips in this kit numbered vertically 1 through 50 on both sides. One of them will be even numbered; the other will be odd numbered.\n\nLocate your eye patch and place it on either eye. Do your best to adjust it so that no light enters. This can be accomplished by placing the band at about a 45 degree angle toward the top of your head rather than directly behind your head. You can also apply slight pressure to the patch with your finger to obtain a good seal around your eye. Do not close your covered eye during the exercises. This is what the eye patch is for.\n\nSet each of the strips of paper on a table about shoulder width apart so that when you lean over and look down they are directly below your eyes. Choose a table that is low enough (or sit high enough) so that you can lean over the strips and look down on them while maintaining a distance of about 18 inches. One side of the strip has larger numbers for those who cannot see the smaller numbers on the other side of the strip. If you cannot see the larger numbers clearly from 18 inches, move closer or farther from them to obtain the best clarity. If you move closer, move the strips closer together. If you move farther from the table, move the strips farther apart as well.\n\nLean over the table and center your open eye between the two strips. You should be able to see both sets of numbers without moving your head; move only your eye.\n\nBegin by focusing on the number 1. Shift your eye without moving your head to the number 2 on the other strip. Shift your eye back to 3 and so on.\n\nWork all the way down to 50 then back up to 1 for each eye for the time duration specified in the training routines. Completely focus on each number before moving to the next. You can either count aloud or silently, but be sure to focus on the number clearly before saying it.\n\nAs you progress, either move closer to the strips or move the strips farther apart on the table. This will increase the difficulty of the exercise by working your eyes farther in both directions.\n\nYour last goal for this exercise is to increase your speed of focusing and seeing each number without moving your head. Remember, the goals are speed, clarity, and precision. Do not simply focus on the strips or a group of numbers. Find each number in sequence and clearly focus on it before moving to the next.";
    public static final int[] pinballImgIds = {R.drawable.p41, R.drawable.p42, R.drawable.p43};

    public static final String inOutL1Desc = "Place the large chart labeled “#5 – OUT” on a wall so that it’s at eye level if you were seated in front of it. Choose a wall where you can face the chart and be seated between 7 and 20 feet from the wall.\n\nSit down facing the chart at a distance between 7 and 20 feet. Choose a distance from which the top letter “E” is distinguishable but not perfectly clear. It is important that the “E” is slightly blurry, but still distinguishable. If the “E” is perfectly clear from 20 feet than use a smaller line on the chart. If the E is not distinguishable from 7 feet you can print a larger E on your computer and tape it above the chart. As your vision improves you will progress to using the E on the chart.\n\nPlace your eye patch over either eye and be sure that there is complete darkness when you open this eye. Adjust the eye patch as necessary or hold slight pressure on it with your finger to obtain total darkness. Focus on the “E” or the first letter of whichever line you have chosen and record the distance of your chair from the wall and which row of letters you read.\n\nPlace your eye patch over your other eye and perform the same exercise, recording the distance of the chair and the row of letters you read. It is likely each eye will be different depending on your condition.\n\nHold the small chart labeled “#5 - IN” as close to your face as possible while still being able to read it comfortably without eye strain – the closer the better (3-12 inches). Choose a letter on the small chart that you can distinguish, although not perfectly clear, at the closest distance possible. (This will not be a factor if you are nearsighted as you should be able to see all of the letters clearly at close range.) Hold the chart in a position so that if you look just over the top of it you can read the row of letters that you chose earlier (on the wall chart) without moving your head.\n\nBegin the exercise by focusing on the letter on the small chart that you have chosen. Now, smoothly and quickly shift your focus to the letter you chose on the wall chart. Once you have focused on the letter on the wall, again shift your focus smoothly back to the letter on the small chart. Repeat this sequence over and over.\n\nInitially you will find that it takes a couple seconds to focus as you shift between charts. As you progress you should be able to smoothly and quickly change focus between the two charts, and the row of letters you chose on both charts should become clearer. When this occurs you have two options: either move your chair back one foot or choose the next row of smaller letters. You can also place the smaller chart closer to your face so that it requires a little more effort to focus on the text or choose a smaller letter on the small chart.";
    public static final int[] inOutL1ImgIds = {R.drawable.p51, R.drawable.p52};

    public static final String inOutL2Desc = "Level two requires only to perform the same exercise with both eyes uncovered. Once you have invested time training each eye individually, you will perform this exercise with both eyes open to train your eyes to work together as a team to obtain the best clarity possible.";
    public static final int[] inOutL2ImgIds = {};

    public static final String stringBeadsDesc = "Find the beaded string provided in your vision training kit.\n\nSit comfortably with your elbows on a table and hold one end of the string at the tip of your nose. Remove anything in the background that is the same color as the string so the colors will not blend together.\n\nHold the other end of the string farther in front of you between your thumb and index finger. Your outstretched hand should be slightly lower than your nose so that the string is sloped slightly downward and completely taut. As you look down the string, your hands and arms should be off to the sides, not above or below the string. Only your fingertips should be in line with the string.\n\nFocus on the far end of the string near your thumb. The string should appear as two strings, forming a V shape with the open end of the V near your face and the closed end coming to a point near the fingers of your outstretched hand.\n\nSlowly and smoothly bring your focus up the string and stop at the bead farthest from you. As your focus moves up the string, the intersection of what appears as two strings should move up the string as well. This will appear as an X with the upper portion of the X smaller than the lower portion. Try to hold the intersection of the two strings on the bead for a count of three.\n\nAgain, begin to transfer your focus smoothly from the farthest bead along the string to the closest bead and hold for another count of three. The intersection of the two strings will move up the string as you change focus and come to rest on the other bead. Try to hold the intersection on the closest bead to you for another count of three. Think of changing your focus as commanding your muscles to pull the intersection up the string. If you have any trouble, look away for a few moments or perform the Distant Night exercise.\n\nFinally, bring your focus up the string to your nose. The string should now appear as a V again, except it will be in the opposite direction with the open end of the V near your outstretched hand and the closed end coming to a point near your nose.\n\nHold your focus on the string as close to your nose as possible for another count of three.\n\nBegin focusing back down the string in the opposite direction. Stop at each of the beads for a count of three, holding the intersection on the bead.\n\nThe key to this exercise is focusing smoothly up and down the string. Hold the intersection exactly on the beads of the two pieces of string you seem to see. Initially your eyes will be very jumpy as you focus up and down the string. It may be difficult to hold your focus as your eyes will want to continually move. Learn to control this. Smooth, slow, and precise is the name of the game!\n\nAs you become more advanced, try to stop and hold the intersection anywhere on the string for a full count of five.";
    public static final int[] stringBeadsImgIds = {R.drawable.p61, R.drawable.p62, R.drawable.p63, R.drawable.p64, R.drawable.p65};

    public static final String eyesWideOpenDesc = "Place the large “#5 – OUT” chart on the wall in front of you at eye level as you did while performing the In & Out exercise.\n\nPlace your chair at the same distance as before and focus on the same line that appeared slightly blurry.\n\nTightly squeeze your eyes closed and inhale a deep breath. Flex all the muscles in your face and clench your fists. Try to push the air out of your lungs and into your head, but do not open your nose or mouth (as if you were trying to lift a heavy object). Continue holding your breath and squeezing your face for a count of three. Use caution while performing this exercise. Do not push or clench so hard that it becomes uncomfortable. Just use enough tension so that it’s noticeable.\n\nNow exhale, forcing all the air out through your nose and mouth, relaxing all the muscles in your body. At the same time, open your eyes as wide as you can and focus on the row of letters you selected. The letters should briefly appear very clear. Try to hold this clarity as long as you can with your eyes wide open. Once you lose this clarity, close your eyes and relax for a few moments.\n\nRepeat this as directed in the training routines.";
    public static final int[] eyesWideOpenImgIds = {R.drawable.p71, R.drawable.p72};

    public static final String muscleMassageDesc = "Sit relaxed in a comfortable position.\n\nPlace your middle and index fingers together on the upper bridge of your nose.\n\nMove your fingertips outward toward your temples, applying gentle pressure just below your brow bones and above your eyelids. Do not apply any pressure directly on your eyelids, just slightly above them along the hard, bony area.\n\nAs you reach your temples, massage for a few moments in a circular motion.\n\nDo the same thing along the bony portion just below your eyes, working outward toward your temples. When you reach your temples, again massage in a circular motion.\n\nDo not apply any pressure to your eyelids or eyeballs when massaging.\n\nAlways follow your massage exercise by briefly performing the Distant Night exercise or a relaxation technique.";
    public static final int[] muscleMassageImgIds = {R.drawable.p81, R.drawable.p82};

}
